<?php
namespace Project\Controller;

class Acf {
	private static $instance = null;
	public static function get_instance() {
		if ( is_null( self::$instance ) ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	function __construct() {
		add_action( 'acf/include_fields', function () {
			if ( !function_exists( 'acf_add_local_field_group' ) ) {
				return;
			}

			acf_add_local_field_group( array(
				'key'                   => 'group_66dbb700ee8fd',
				'title'                 => 'Elements',
				'fields'                => array(
					array(
						'key'               => 'field_66dbb70174d1f',
						'label'             => 'Testimonials',
						'name'              => 'testimonials',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'table',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 0,
						'collapsed'         => '',
						'button_label'      => 'Add Row',
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_66dbb742096c4',
								'label'             => 'Avatar',
								'name'              => 'avatar',
								'aria-label'        => '',
								'type'              => 'image',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'id',
								'library'           => 'all',
								'min_width'         => '',
								'min_height'        => '',
								'min_size'          => '',
								'max_width'         => '',
								'max_height'        => '',
								'max_size'          => '',
								'mime_types'        => '',
								'preview_size'      => 'medium',
								'parent_repeater'   => 'field_66dbb70174d1f',
							),
							array(
								'key'               => 'field_66dbb74f096c5',
								'label'             => 'Text',
								'name'              => 'text',
								'aria-label'        => '',
								'type'              => 'textarea',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'rows'              => '',
								'placeholder'       => '',
								'new_lines'         => '',
								'parent_repeater'   => 'field_66dbb70174d1f',
							),
							array(
								'key'               => 'field_66dbb75b096c6',
								'label'             => 'Star',
								'name'              => 'star',
								'aria-label'        => '',
								'type'              => 'number',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'min'               => '',
								'max'               => '',
								'placeholder'       => '',
								'step'              => '',
								'prepend'           => '',
								'append'            => '',
								'parent_repeater'   => 'field_66dbb70174d1f',
							),
							array(
								'key'               => 'field_66dbb767096c7',
								'label'             => 'Name',
								'name'              => 'name',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'parent_repeater'   => 'field_66dbb70174d1f',
							),
							array(
								'key'               => 'field_66dbb776096c8',
								'label'             => 'Position',
								'name'              => 'position',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'parent_repeater'   => 'field_66dbb70174d1f',
							),
						),
					),
					array(
						'key'               => 'field_66e10d419ece7',
						'label'             => 'Slide Pc',
						'name'              => 'slide_pc',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'table',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 0,
						'collapsed'         => '',
						'button_label'      => 'Add Row',
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_66e10d519ece8',
								'label'             => 'Image',
								'name'              => 'image',
								'aria-label'        => '',
								'type'              => 'image',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'id',
								'library'           => '',
								'min_width'         => '',
								'min_height'        => '',
								'min_size'          => '',
								'max_width'         => '',
								'max_height'        => '',
								'max_size'          => '',
								'mime_types'        => '',
								'preview_size'      => 'medium',
								'parent_repeater'   => 'field_66e10d419ece7',
							),
							array(
								'key'               => 'field_66e10d5b9ece9',
								'label'             => 'Link',
								'name'              => 'link',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'parent_repeater'   => 'field_66e10d419ece7',
							),
						),
					),
					array(
						'key'               => 'field_66e10d639ecea',
						'label'             => 'Slide mobile',
						'name'              => 'slide_mobile',
						'aria-label'        => '',
						'type'              => 'repeater',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'table',
						'pagination'        => 0,
						'min'               => 0,
						'max'               => 0,
						'collapsed'         => '',
						'button_label'      => 'Add Row',
						'rows_per_page'     => 20,
						'sub_fields'        => array(
							array(
								'key'               => 'field_66e10d639eceb',
								'label'             => 'Image',
								'name'              => 'image',
								'aria-label'        => '',
								'type'              => 'image',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'return_format'     => 'id',
								'library'           => 'all',
								'min_width'         => '',
								'min_height'        => '',
								'min_size'          => '',
								'max_width'         => '',
								'max_height'        => '',
								'max_size'          => '',
								'mime_types'        => '',
								'preview_size'      => 'medium',
								'parent_repeater'   => 'field_66e10d639ecea',
							),
							array(
								'key'               => 'field_66e10d639ecec',
								'label'             => 'Link',
								'name'              => 'link',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
								'parent_repeater'   => 'field_66e10d639ecea',
							),
						),
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'options_page',
							'operator' => '==',
							'value'    => 'site-settings',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'normal',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => '',
				'show_in_rest'          => 0,
			) );
		} );

		add_action( 'acf/init', function () {
			acf_add_options_page( array(
				'page_title' => 'Site settings',
				'menu_slug'  => 'site-settings',
				'position'   => '',
				'redirect'   => false,
			) );
		} );


	}
}